id: adco
name: Advancement Count
description: "Awards players a certain number of points for each advancement they complete. The total number for each player can then be viewed in the Tab list."
author: "2mal3"
version: "v1.0.0"
minecraft: "1.19"

output: build

data_pack:
    name: Advancement-Count
    description: "v1.0.0"
    load:
        - src

pipeline:
    - beet.contrib.rename_files
    - mecha
    - plugins.remove_empty_functions
    - plugins.installation_advancement
require:
    - bolt

meta:
    version: 10000

    bolt:
        entrypoint:
            - adco:advancements

    vanilla:
        version: "1.19.3"

    rename_files:
        data_pack:
            match:
                functions: "adco:*"
            find: "((?!.*-).+)"
            replace: '\1/child'

    installation_advancement:
        icon:
            item: minecraft:knowledge_book
