id: "adco"
name: "Advancement Count"
description: "Awards players a certain number of points for each advancement they complete. The total number for each player can then be viewed in the Tab list."
author: "2mal3"
version: "v1.0.2"
minecraft: "1.20"

output: "build"

data_pack:
    name: "Advancement-Count"
    description: "v1.0.2"
    load:
        - "src"
        - pack.png: "pack.png"

pipeline:
    - mecha
    - plugins.remove_empty_functions
    - plugins.installation_advancement
require:
    - bolt

meta:
    version: 10002

    bolt:
        entrypoint:
            - adco:advancements

    vanilla:
        version: "1.20.1"

    installation_advancement:
        icon:
            item: minecraft:knowledge_book
