name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  NAME: 'Advancement-Count'
  MODRINTH_ID: '2tEdxXOF'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.lock

      - name: Build
        run: beet

      - name: Squash datapack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: v0.4.0
          artifact_name: datapack-raw
          options: |
            pack_directory = "build/${{ env.NAME }}"
            output_file_path = "${{ env.NAME }}.zip"
      - name: Add secondary files to datapack
        run: zip -u ${{ env.NAME }} LICENSE.txt README.md CHANGELOG.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            CHANGELOG.md
            ${{ env.NAME }}.zip

  release-github:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.NAME }} ${{github.ref_name}}
          body_path: CHANGELOG.md
          files: |
            ${{ env.NAME }}.zip

  release-modrinth:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish on Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-unfeature-mode: intersection
          files: |
            ${{ env.NAME }}.zip
          name: ${{ env.NAME }} ${{github.ref_name}}
          version: ${{github.ref_name}}
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: datapack
          game-versions: |
            1.20.6
